### ISSUE TITLE
Replying to thread jumps to nonexistant pages past end of thread

### ISSUE THREAD

**Issue by thehans** [Awful/Awful.apk#260]
I have posts per page set to 10 in Awful app(as opposed to 40 default), and when I post a reply to any thread, it attempts to go to something like 4 times the last page number, which displays as a blank screen.

**Comment by baka-kaba** [comment]
Is this still a thing? I'm not seeing it on the latest build, works exactly as I'd expect (tested on a thread with 164 pages and one with 1000+)

**Comment by Sereri** [comment]
Not happening to me either. Considering it's 1.5y old and possibly fixed ...
