### ISSUE TITLE
Duplicate Thread Actions window

### ISSUE THREAD

**Issue by anthonypants** [Awful/Awful.apk#287]
Phone: Nexus One
Android: 2.3.6 (GRK39F)
Awful: 3.0.7

In a thread view, the top-right drop-down arrow loads a "Select an Action" window. The items in this list are Post reply, Bookmark, Rate thread, etc. If you hit the Back button, it looks like a "Thread actions" window was hidden behind it. The items in this list are Post Reply, Unbookmark, Rate thread, etc. If you hit the Back button, the window closes and the thread view returns to normal.

The "Thread actions" window also appears if you select an item in the "Select an Action" list; i.e., if you go to post a reply and back out, rate the thread, etc. If you follow through with making a post using the "Select an Action" window, the "Thread actions" window will appear briefly while you are kicked back to the thread view, but will not persist as the thread is refreshed. (This was how I first discovered the second window.)

This was introduced a few revisions ago in the beta, but since I'm a Gingerbread user I figured I would wait for someone else to report it. But nobody did, so it's probably just affecting Gingerbread. Gingerbread users are more Awful than this app.

**Comment by Sereri** [comment]
I ripped out the second one when dropping GB. Considering this solved
