### ISSUE TITLE
Awful.app Thread Tags

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#300]
(Let's see if this works)

Hey, @Ridilla and Jim Murtha (possibly via @nolanw maybe?)
Awful.apk will use your tread tags in an upcoming update. I'd like to add you to our contributor list (which consists of SA usernames). What names do I add?

**Comment by Ridilla** [comment]
Oooohhhhh going to start a war!

Considering this is forums-only you can just use "The Dave", thanks for the
consideration.

**Comment by diabolik900** [comment]
I'm Diabolik900, both here and on the forums. 

Thanks!

**Comment by Sereri** [comment]
Added you both in 2e867c26dc5e18fb7c391c951001eb7e94231224
