### ISSUE TITLE
Fix the film dump

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#324]
Film dump has no thread tags but ratings, everything looks terrible. Introduce rating tags from awful thread tags.

**Comment by baka-kaba** [comment]
I did a thing (#326), it still looks pretty bad but at least it works!

I just got the functionality down really, I had a go at tweaking the layouts to make it look nicer but it was causing issues with normal forums, and I've had enough right now.

Another stopgap would be to put the rating drawable in the thread tag view instead (there's a little hack in the code for messing with the layout when it's a Film Dump rating, it could be done there), but really the layouts need reworking properly I think, to handle all these special cases gracefully - there's the double-tag threads too
