### ISSUE TITLE
Forum list loads twice

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#331]
For some reason the thread list loads twice or at least the method handling the finish loading reloads the listview twice. This causes the list to jump back to the top twice.

**Comment by baka-kaba** [comment]
Things load *at least* twice, I've seen three or even four times before (watching the blue loading bar). It makes me wonder if part of the logout issue is down to the site putting a block on clients that are spamming requests

I've looked into this before, ThreadDisplayFragment has a couple of loaders that get restarted a lot, if I remember right they even restart themselves until nothing changes from one load to the next. I was trying to trim it down and make it easier to wrangle, but it might be better with an overhaul
