### ISSUE TITLE
Square forum tags?

### ISSUE THREAD

**Issue by baka-kaba** [Awful/Awful.apk#349]
Do we want this for the forum list? I tried it out and it's easy to implement - I used the `ElementCollection` thing, like with the review/secondary tags, it just needs some... square tags from somewhere. There are 3 or 4 already - do we have any anywhere else? It would match the rest of the app better and give a bit more room for the titles

For a laugh I tried adding a theme-dependent tinting call on the `getDrawable()` call, so they're all green for yospos, yellow for amberpos etc (it uses the colour from the theme). You can have a look at it [here](https://github.com/baka-kaba/Awful.apk/tree/ForumTags) if you like, it's bad inefficient code but I was just trying it out quickly

It only affects assets accessed through that `ElementCollection` class, so not normal tags, but I could add them to a Tags class if people are cool with it? It's a different way of accessing things (calling the static class with the URL instead of parsing a filename out and getting `R.drawable.filename`), but it should be easier to maintain, provide defaults if they ever change a URL, that kind of thing

**Comment by Sereri** [comment]
Problem is, the tags were now using are a byproduct of the Awful iOS app. They don't use forum tags so there are only those where the forum tag is also a thread tag (like GiP).

I mean we could ask @diabolik900 and @Ridilla, but at the moment I don't think it's possible

**Comment by diabolik900** [comment]
Making forums tags in the style of our square thread tags should theoretically be easier than the thread tags because they all follow the same simple style. 

I have some free time coming up over the weekend where I could probably work on them if there's interest.

**Comment by baka-kaba** [comment]
It's pretty much ready to go if you're willing to make them, yeah! And if Sereri's cool with the change

If you wanted we could incorporate the frog silhouette somehow for the two-tone pattern, like taking up the bottom/right half of the square, to help give the app a little more character. I'm not a designer in case you hadn't guessed!

Also a generic icon would be useful too, as a placeholder for when new forums are added or something's changed. We can just have it use the icon from the webpage if necessary, but it'll look pretty rubbish

**Comment by Sereri** [comment]
Some time has passed and I made a generic forum tag that works by tinting the white for the square color and setting the background of the imageview to the color of the background (good job on github having a white background)
![forumtagtest](https://cloud.githubusercontent.com/assets/803440/14994898/752bd62c-1172-11e6-8440-25005f374123.png)

Problem is it looks bad.
![screenshot_20160503-210611](https://cloud.githubusercontent.com/assets/803440/14995022/07035cb4-1173-11e6-9c69-1bc47c6a9511.png)

Any ideas for improvement?

**Comment by baka-kaba** [comment]
The standard two-colour anonymous profile pic icon, only with a frog. It would be good to have the frog in there anyway (like where the mini square is, or as part of an outer border) just to use the branding.

I think we'd need something to add abbreviation text though, it's not like anyone recognises the colours. Maybe a class that creates drawables, with a hardcoded list of forum IDs mapped to abbreviations, and then it just adds the text on the drawable or whatever

**Comment by baka-kaba** [comment]
I made a little change in #419, I put the tinting implementation in the SquareForumTag class, and I tried adding some desaturation since the website tag colours are pretty bold, so it might be worth playing with. Plus we could do theme-aware tinting later if anyone cares

**Comment by Sereri** [comment]
Transitioning from the now closed pull-request, this is the image I'd like to improve upon:
https://cloud.githubusercontent.com/assets/803440/15335405/749c6ff4-1c72-11e6-94fd-683bc6d75035.png
It's mostly transparent with a white square at the bottom left. The transparent part is lets a background color shine through while the white part is tinted with a different color.

Because of this any texturing would work by applying an alpha value of black to, well let's be honest, make it a bit darker

Currently looks like this:
![screenshot_20160524-155405](https://cloud.githubusercontent.com/assets/803440/15506444/f7ec1d96-21c7-11e6-8090-b17475e05eaf.png)

**Comment by baka-kaba** [comment]
I vectorised the ol' frog (which should be useful as an asset at least) and tried this out

![screenshot_20160531-062931](https://cloud.githubusercontent.com/assets/6281947/15664387/2099b2de-26fb-11e6-81d4-d381f48b15db.png)

It's basically a LayerDrawable in XML, with a rounded rectangle Shape for the background and the frog as another layer on top. The nice thing is you can give each layer its own ID, and then colour them however you like, so you're not just limited to foreground and background colours

Some of the colour combos are, uh, a bit unusual though. It might be worth trying to work the other colours in there (there's like a light and a dark tint of both main colours in the website tags, I think?). Texturing's probably possible with the right blending mode, but really I think it depends what kind of texture you want. I'm not a designer so I just know how to make things look bad, which is one of the plus points of the whole material design thing - everything's flat and clean

I added a FrogTag branch on my repo if you want to play around with it

**Comment by Sereri** [comment]
I guess I could live with the frog but I think there'll be might be many tears about it. Not sure how to handle it since A/B testing for apks is not a thing in Google Play. Maybe post 2 apks in the thread?

**Comment by baka-kaba** [comment]
I'm not too fussed about the frog, if you hate it - I just wanted to try it out. I thought people loved that little guy though, especially the old spinning loader frog...

If you want to test it out (or anything else) I could just put the new stuff in another version of the SquareForumTag class. Could have a menu toggle, or if you want an integrated A/B thing we could just hash usernames on app startup and assign them based on odd/even hashes, and just query that value whenever you have a variation to offer

**Comment by Sereri** [comment]
It's probably a bad idea but I guess if you could put the new stuff in another version of the SquareForumTag class, you could set the frog as the default and add a setting to switch to the more traditional type. I'm usually against adding more settings at this point, but the forum index page has like 4 items so it's not that overcrowded yet. There's lots of people mourning the spinning frog but also lots of people sick of it. This would satisfy both camps.

**Comment by baka-kaba** [comment]
Ehhh, seems like it would be better to just settle on one design and stick with it. If you don't like the frog then the frog can :getout:, no point having a bunch of random customisations that need to be maintained. I mean it could work for some easter-egg 'frog mode' or whatever, but I don't think anyone cares about doing that

I mean the tag is there already and easy enough to swap in with a flag, if you think it's worth it

**Comment by Sereri** [comment]
App is now totally frogged.
