### ISSUE TITLE
Title regression

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#433]
The current beta build has a regression with the title. When returning to the thread view for example the correct title will appear, then be replaced by the title of the forum display view

![screenshot_20160607-104236](https://cloud.githubusercontent.com/assets/803440/15851368/b9423640-2c9c-11e6-9434-0938ccd2a736.png)

**Comment by baka-kaba** [comment]
Fixed by #583 (fragments can't push titles anymore, they notify and the view pager decides on a title based on the current page)
