### ISSUE TITLE
Show Image Inline doesn't work for attachments

### ISSUE THREAD

**Issue by baka-kaba** [Awful/Awful.apk#486]
Basically this happens
* the site html uses relative urls for attachment images (``href="attachment.php?postid=3243545"``)
* when the app parses it, if the images are turned into links instead, the link in the app html stays relative
* when the link options dialog runs, a resolved absolute url gets passed through (``https://forums.somethingawful.com/attachment.php?postid=3243545``)
* that's passed to the Javascript that replaces the image - it tries to find an ``a`` element with a matching ``href``
* there isn't one because the relative and absolute urls don't match eh

**Comment by Sereri** [comment]
Fixed in #594
