### ISSUE TITLE
Settings dividers/titles

### ISSUE THREAD

**Issue by baka-kaba** [Awful/Awful.apk#489]
I don't know when it happened, but the settings preferences don't have any visible dividers anymore, and it looks pretty bad. It *might* be something to do with an internal library change using ``RecyclerView``s for preference lists, and a lack of default dividers, or something. Anyway it needs fixing up

Also the title should really update to show the title of the submenu you're in, or just "Settings" if you're in the root. Also the title font is different to the rest of the app, looks bold or something. Probably not using the same base theme?

**Comment by Sereri** [comment]
All of the above and it's also missing a back arrow.

**Comment by baka-kaba** [comment]
The dividers were fixed in #515 , titlebar stuff still needs doing

**Comment by baka-kaba** [comment]
Fixed up in #523 along with some other things
