### ISSUE TITLE
Signatures are not parsed in FYAD

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#567]
The post signatures are not parsed in FYAD since they are not part of the 'complete_shit' div but instead reside next to it. I don't know if that was broken in the recent transition or never worked in the first place.

**Comment by baka-kaba** [comment]
God
yeah it looks like those were never getting parsed, unless moving it to a separate div is a recent thing in the web dev adventures. The post content was always the html from ``.complete_shit`` if it exists, otherwise just ``.postbody``

**Comment by baka-kaba** [comment]
All right that was fairly quick, fixed in #568
