### ISSUE TITLE
Navigation drawer is displaying forum categories instead of parent forums

### ISSUE THREAD

**Issue by baka-kaba** [Awful/Awful.apk#569]
I've noticed the links that are meant to show the hierarchy for the current thread (its parent forum, then "The SA Forums") is actually showing the parent forum's category (e.g. Main) instead.
These don't go anywhere, they're dummy forums that are only meant to appear on the forums list as a section header. Not sure when this happened but that needs fixing - something's probably passing the wrong ``Forum`` object in

**Comment by Sereri** [comment]
I think I know why they're not working, Lowtax fucking with the html. He is changing the DOM after the fact. However our library is still getting the original DOM so the app sees the links to the parent forums that he removes as well.
Compare ```
<div class="breadcrumbs"><span class="mainbodytextlarge"><a class="index" href="/" title="Forums index">«</a>&nbsp;<a href="forumdisplay.php?forumid=273" class="up"><span><a href="/">The Something Awful Forums</a><a href="forumdisplay.php?forumid=48">Main</a><a href="forumdisplay.php?forumid=273">GBS: Home of xenForo 2.0</a></span>GBS: Home of xenForo 2.0</a> › <a href="showthread.php?threadid=3847240" class="bclast">Do we have too many polls? (Poll)</a></span></div>```
vs ```
<div class="breadcrumbs"><span class="mainbodytextlarge"><b><a href="/">The Something Awful Forums</a> &gt; <a href="forumdisplay.php?forumid=48">Main</a> &gt; <a href="forumdisplay.php?forumid=273">GBS: Home of xenForo 2.0</a> &gt; <a href="showthread.php?threadid=3847240" class="bclast">Do we have too many polls? (Poll)</a></b></span></div>```

**Comment by baka-kaba** [comment]
Finally got around to this - you were right, and I'd probably never have noticed that happening. The parsing code was picking the first forum in the breadcrumb list though, assuming there'd only be one forum in there. Semantically it should have been picking the last (which it is now), which would have avoided the issue in the first place

Fixed in #589
