### ISSUE TITLE
Twitter images are broken

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#572]
Images are currently broken in twitter embeds.

They probably updated their widget.js to that point that it's incompatible with ours

**Comment by baka-kaba** [comment]
Wonder if this just needs the Twitter script replacing

How come we store those locally anyway, instead of loading the latest version? Security?

**Comment by Sereri** [comment]
I think it just didn't work with the remote version. Although I don't actually remember.

See https://forums.somethingawful.com/showthread.php?threadid=3510131&pagenumber=213&perpage=40#post457632494

**Comment by baka-kaba** [comment]
I just replaced the contents of ``twitterwidget.js`` with the script here:
https://dev.twitter.com/web/javascript/loading
and it was working on my emulator... but now it isn't working anywhere

**Comment by Sereri** [comment]
I got it. A combination of updating the twitterwidget.js (the version from above looses the race conditions almost every time for me an needs some further work) and adding setDomStorageEnabled(true) to the webview settings

**Comment by Sereri** [comment]
Fixed by #580
