### ISSUE TITLE
Add sharing to embedded videos

### ISSUE THREAD

**Issue by baka-kaba** [Awful/Awful.apk#617]
Right now video links just get replaced by the embedded video, so there's no way to share or get a link to it except by quoting the post and doing it in the reply window

Ideally there'd be a long-press menu on videos, maybe the one we use for images? The only difference I can see is you might want a "get link at current time" option and that would probably be a nightmare to get working consistently.

The easier option would be to keep the link below the video, so people can interact with it the usual way. Or we could have a little link icon instead of the URL text

**Comment by Sereri** [comment]
I think I'm in favor of the link options because having touch listeners on the video might cause problems with the standard functionality

**Comment by Sereri** [comment]
Implemented in #621
