### ISSUE TITLE
Find on page is not correctly

### ISSUE THREAD

**Issue by Sereri** [Awful/Awful.apk#671]
The find on page option in the thread view lays a search field over the toolbar. This is not styled causing it to be very hard to read on light themes and looking bad in dark themes.

The search toolbar should be styled to match the current theme.

**Comment by baka-kaba** [comment]
This is something to do with ``ToolBarStyle`` in the app theme - it inherits from a dark ``ThemeOverlay`` (which is why it's... dark) but that conflicts with the light app themes which want to use dark text. I hate themes!!

**Comment by baka-kaba** [comment]
fixed in 54a5177b6e165933046f738df260bc91bc38dcf7
