### ISSUE TITLE
Twitter bad

### ISSUE THREAD

**Issue by baka-kaba** [Awful/Awful.apk#706]
Tweets aren't loading very well - it looks like they start to embed, but then some of the assets fail to load? Sometimes it's fine, other times it fails with permission denied errors in the DevTools console. Maybe we can handle reloading better, or something? There doesn't seem to be a problem in a desktop browser session so I'm wondering if there's suddenly an issue with our way of doing it

**Comment by Sereri** [comment]
Huh, hadn't had problems for a while. Did they change their code again?

**Comment by baka-kaba** [comment]
I dont think so? It just seems to be choking on some loads, other times it works fine, and I've seen people complaining about it (not specifically mentioning the app, but I haven't seen it happening on my laptop)

I get the feeling the site's a bit overloaded at the moment, and I was wondering if there was anything we could do on our side to get around it

**Comment by baka-kaba** [comment]
Well it seems to be ok now so may as well close this unless it comes up again, not sure why desktop browsers weren't choking but ehh
