### ISSUE TITLE
Probation time display is probably broken

### ISSUE THREAD

**Issue by baka-kaba** [Awful/Awful.apk#710]
Reports suggest the probe bar isn't showing the correct time for when your probation ends (shows the current time right now apparently). It's being worked on on the site, so it'll probably need fixing in the app when it's done. I haven't looked, but at a guess the element we normally look for has gone, so it's defaulting to a value of 0 hours left or whatever

**Comment by AlexandriaOL** [comment]
I can confirm this, but it's not showing up as 0 hours, it's showing up with the right time but with the current time, and the wrong day:

![foo](https://i.imgur.com/GB0ToFw.png)

![bar](https://i.imgur.com/bDGjWgT.png)

If the probe was given around the time they edited the message (13:53, on June 16th), then the probe should end at around 19:53 on June 16th, not "the current time but on the next day" :)

**Comment by baka-kaba** [comment]
Oh yeah, I checked the code and it defaults to 24 hours from now, because... uh I don't know why! Considering most people get probed for 6 hours that would be a better default, but "don't know" would be the best thing to say

Thanks for the screenshot! Once the message is decided, or they add a way to grab the timestamp directly (they're messing with the site at the moment, that's why it broke) we can change it
