### ISSUE TITLE
Unable to see who handed out probations in LC

### ISSUE THREAD

**Issue by cyber-pingu** [Awful/Awful.apk#748]
I used to be able to see which mod handed out probes in the Lepers Colony by tapping on the post and it would unfurl down to show the mods name. Since the most recent update this no longer works.

**Comment by kahays** [comment]
Version 3.8.13 was supposed to solve this, has that update come through for you yet? (Version is listed in `Settings` > `About`)

**Comment by cyber-pingu** [comment]
@kahays yep new version has fixed this.

Cheers
